[FilterPlugin]
; Additional files to include when packaging the plugin with BuildPlugin
/README.md
/QUICKSTART.md
/LICENSE.md
/Tests/...

/Docs/...
/Scripts/...
/Patches/...
/Config/DefaultYarnSpinner.ini
